# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Link Order',
    'version': '1.1',
    'summary': 'Link Production Processs',
    'sequence': 10,
    'description': """ """,
    'category': 'Accounting/Accounting',
    'depends': ['sale_management', 'contacts', 'purchase', 'accountant', 'mrp', 'stock','hr_payroll', 'hr_attendance'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/overtime_data.xml', 
        # 'data/hr_salary_rule_data.xml',
        'views/production_order_views.xml',
        'views/sale_order_views.xml',
        'views/company_views.xml',
        'views/lor.xml',
        'views/product_template_view.xml',
        'views/material_issue_views.xml',
        'views/stock_picking_view.xml',
        'views/account_move_view.xml',
        'views/purchase_order_view.xml',
        # 'views/stock_lot_view.xml',
        'views/hr_contract_view.xml',
        'report/report_custom_proforma_document.xml',
        # 'report/report_proforma_template.xml',
        'wizards/production_order.xml',
        # 'wizards/overtime_wizard_view.xml',
        'report/standard_report_layout.xml',
        'report/production_order_form_report.xml',
        'report/report_lor_template.xml',
        'report/lor_report_template.xml',
        'report/material_issue_form_report.xml',
        'report/material_issue_form_template.xml',
        'report/report_finished_goods_transfer.xml',
        'report/finished_goods_transfer_template.xml',
        # 'report/tax_invoice_report.xml',
        # 'report/tax_invoice_report_template.xml',
        'report/sales_report_partner.xml',
        'report/sales_report_template.xml',
        'report/partner_purchase_report.xml',
        'report/partner_purchase_report_template.xml',
        # 'report/closing_stock_template.xml',
        # 'report/closing_stock_report.xml',
        # 'report/stock_aging_report_template.xml',
        # 'report/stock_aging_report.xml',
        # 'report/stock_report_template.xml',
        # 'report/stock_report.xml',
        # 'report/categorized_stock_report_template.xml',
        # 'report/categorized_stock_report.xml',

        
        
    ],
   
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
